import {
    profile,
    user1,
    user2,
    user3,
    user4,
    user5,
    user6,
    user7,
    user8,
    user9,
  } from "../../assets/images";
  
  export const userData = [
    {
      id: 1,
      name: "Peggie",
      age: 28,
      hobbies: ["Concerts", "Festivals", "Photography"],
      bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life. When I'm not behind the lens, you'll find me immersing myself in the energy of live music at concerts and festivals. Exploring new cultures and cuisines is my idea of a perfect adventure. Let's share stories over a cup of coffee and see where our shared passions take us!",
      distance: "3 miles away",
      imgPath: user1,
    },
    {
      id: 2,
      name: "Diana",
      age: 30,
      hobbies: ["Hiking", "Cooking", "Music"],
      bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together. Seeking someone to share adventures and good food with.",
      distance: "10 miles away",
      imgPath: user2,
    },
    {
      id: 3,
      name: "Sophie",
      age: 26,
      hobbies: ["Painting", "Yoga", "Traveling"],
      bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar. Let's embark on a journey of self-discovery together, exploring the world and creating masterpieces along the way.",
      distance: "2 miles away",
      imgPath: user3,
    },
    {
      id: 4,
      name: "Betty",
      age: 32,
      hobbies: ["Soccer", "Cooking", "Movies"],
      bio: "Hi there! I'm Betty, a soccer lover who finds joy in the kitchen and the magic of movies. Let's kick a ball around and then cook up a storm together. Seeking someone to share adventures and good food with.",
      distance: "5 miles away",
      imgPath: user4,
    },
    {
      id: 5,
      name: "Lily",
      age: 29,
      hobbies: ["Dancing", "Reading", "Hiking"],
      bio: "Hola! I'm Lily, a dance lover who finds joy in the rhythm of life. Books are my escape, and hiking fuels my spirit. Let's dance under the stars and get lost in stories over a cup of coffee. Eager to meet someone to share life's dance with.",
      distance: "7 miles away",
      imgPath: user5,
    },
    {
      id: 6,
      name: "Chiara",
      age: 28,
      hobbies: ["Singing", "Writing", "Sailing"],
      bio: "Ciao! I'm Chiara, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
      distance: "4 miles away",
      imgPath: user6,
    },
    {
      id: 7,
      name: "Emma",
      age: 27,
      hobbies: ["Singing", "Writing", "Sailing"],
      bio: "Hi there! I'm Emma, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
      distance: "4 miles away",
      imgPath: user7,
    },
    {
      id: 8,
      name: "Sarah",
      age: 29,
      hobbies: ["Surfing", "Gardening", "Painting"],
      bio: "Hi there! I'm Sarah, a surfer who finds joy in the garden and the magic of painting. Let's ride the waves and then paint up a storm together. Seeking someone to share adventures and good food with.",
      distance: "8 miles away",
      imgPath: user8,
    },
    {
      id: 9,
      name: "Olivia",
      age: 28,
      hobbies: ["Yoga", "Hiking", "Photography"],
      bio: "Hello, I'm Olivia, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
      distance: "9 miles away",
      imgPath: user9,
    },
  ];
  
  export const chatData = [
    {
      id: 1,
      name: "Priscilda",
      imgUrl: user1,
      age: 25,
      isOnline: true,
      lastMessage:
        "Isso parece muito divertido. Gostaria de ir junto algum dia?",
      date: "2023-10-15",
      timeSent: "5 mins",
      chat: [
        {
          sender: "me",
          message: "Olá! Como vai?",
          timestamp: "10:00 AM",
        },
        {
          sender: "Betty",
          message: "Estou ótima, obrigada!",
          timestamp: "10:05 AM",
        },
        {
          sender: "me",
          message: "Tem planos empolgantes para o fim de semana? 😊",
          timestamp: "10:10 AM",
        },
        {
          sender: "Betty",
          message: "Sim, estou pensando em fazer uma trilha. 🏞️ E você?",
          timestamp: "10:15 AM",
        },
        {
          sender: "me",
          message: "Isso parece incrível! Talvez eu me junte. 🥾",
          timestamp: "10:20 AM",
        },
        {
          sender: "Betty",
          message: "Isso seria ótimo! Quanto mais, melhor. 🌟",
          timestamp: "10:25 AM",
        },
      ],
    },
    {
      id: 2,
      name: "Owelza",
      imgUrl: user2,
      age: 20,
      isOnline: false,
      lastMessage: "Claro, vamos fazer isso. Quando você está livre?",
      date: "2023-10-14",
      timeSent: "10 mins",
      chat: [
        {
          sender: "me",
          message: "Ei Charlie, como você tem estado?",
          timestamp: "11:00 AM",
        },
        {
          sender: "Charlie",
          message: "Tenho estado bem. E você?",
          timestamp: "11:05 AM",
        },
        {
          sender: "me",
          message: "Tenho estado um pouco ocupado, mas me virando. 😊",
          timestamp: "11:10 AM",
        },
        {
          sender: "Charlie",
          message: "Eu entendo. Devemos nos encontrar em breve! ☕",
          timestamp: "11:15 AM",
        },
        {
          sender: "me",
          message: "Com certeza! Vamos planejar algo para este fim de semana. 🎉",
          timestamp: "11:20 AM",
        },
        {
          sender: "Charlie",
          message: "Claro, isso parece bom. Quando você está livre? 🗓️",
          timestamp: "11:25 AM",
        },
        {
          sender: "me",
          message: "Estou livre no sábado à tarde. E você? 🌤️",
          timestamp: "11:30 AM",
        },
        {
          sender: "Charlie",
          message: "Sábado também funciona para mim! Vamos nos encontrar no nosso lugar habitual. 🍔",
          timestamp: "11:35 AM",
        },
        {
          sender: "me",
          message: "Parece um plano! Até lá. 👋",
          timestamp: "11:40 AM",
        },
      ],
    },
    {
      id: 3,
      name: "Joelma",
      imgUrl: user3,
      age: 21,
      isOnline: true,
      lastMessage: "Parece um plano! Vamos fazer acontecer.",
      date: "2023-10-11",
      timeSent: "25 mins",
      chat: [
        {
          sender: "me",
          message: "Olá Oliver, como está sendo seu dia?",
          timestamp: "14:00",
        },
        {
          sender: "Oliver",
          message: "Está sendo ótimo! Aproveitando o sol. E você?",
          timestamp: "14:05",
        },
        {
          sender: "me",
          message: "Que maravilha! Estou apenas terminando um pouco de trabalho. 💻",
          timestamp: "14:10",
        },
        {
          sender: "Oliver",
          message: "Não trabalhe demais! Certifique-se de fazer pausas. 🌞",
          timestamp: "14:15",
        },
        {
          sender: "me",
          message:
            "Com certeza, pausas são necessárias. Planejando algo divertido para a noite? 🎉",
          timestamp: "14:20",
        },
        {
          sender: "Oliver",
          message: "Eu talvez vá para a academia mais tarde. Preciso desestressar um pouco. 💪",
          timestamp: "14:25",
        },
        {
          sender: "me",
          message: "Isso é uma ótima ideia! Deveria me juntar a você em algum momento. 🏋️‍♂️",
          timestamp: "14:30",
        },
        {
          sender: "Oliver",
          message: "Com certeza! Quanto mais, melhor. 🤸‍♂️",
          timestamp: "14:35",
        },
      ],
    },
    {
      id: 4,
      name: "Diana",
      imgUrl: user9,
      age: 32,
      isOnline: true,
      lastMessage: "Com certeza! Estou ansiosa por isso.",
      date: "2023-10-10",
      timeSent: "30 mins",
      chat: [
        {
          sender: "me",
          message: "Ei Sophie, como foi sua semana?",
          timestamp: "15:00",
        },
    
        {
          sender: "Sophie",
          message: "Foi ocupada, mas boa. E você?",
          timestamp: "15:05",
        },
        {
          sender: "Sophie",
          message: "E também cansativa.",
          timestamp: "15:05",
        },
        {
          sender: "me",
          message: "A minha também foi bastante agitada, mas estou me virando.",
          timestamp: "15:10",
        },
        {
          sender: "Sophie",
          message: "Que bom ouvir isso. Algum plano empolgante para o fim de semana?",
          timestamp: "15:15",
        },
        {
          sender: "me",
          message:
            "Ainda não, mas estou pensando em conferir aquele novo restaurante no centro da cidade. E você?",
          timestamp: "15:20",
        },
        {
          sender: "Sophie",
          message:
            "Estou planejando ir fazer trilha com alguns amigos. Você deveria se juntar a nós algum dia!",
          timestamp: "15:25",
        },
      ],
    }
    ,
  
    {
      id: 5,
      name: "Ralina",
      imgUrl: user5,
      age: 22,
      isOnline: false,
      lastMessage: "Deixe-me verificar minha agenda e volto para você.",
      date: "2023-10-09",
      timeSent: "35 mins",
      chat: [
        {
          sender: "me",
          message: "Oi William, como vão as coisas?",
          timestamp: "16:00",
        },
        {
          sender: "William",
          message: "As coisas estão indo bem. E você?",
          timestamp: "16:05",
        },
      ],
    },
    {
      id: 6,
      name: "Edna",
      imgUrl: user4,
      age: 23,
      isOnline: true,
      lastMessage: "Parece uma ótima ideia. Vamos fazer acontecer.",
      date: "2023-10-07",
      timeSent: "45 mins",
      chat: [
        {
          sender: "me",
          message: "Ei Jack, como foi sua semana?",
          timestamp: "18:00",
        },
        {
          sender: "Jack",
          message: "Foi ocupada, mas boa. E você?",
          timestamp: "18:05",
        },
      ],
    },
  ];
  
  export const datesData = [
    {
      id: 1,
      imgUrl: user1,
      name: "Priscilda",
      lastName: "Jones",
      age: 25,
      city: "Matola",
      country: "MOZ",
    },
    {
      id: 2,
      imgUrl: user2,
      name: "Owelza",
      lastName: "Quive",
      age: 20,
      city: "Matola",
      country: "MOZ",
    },
    {
      id: 3,
      imgUrl: user3,
      name: "Joelma",
      lastName: "Nataniel",
      age: 21,
      city: "Maputo Cidade",
      country: "MOZ",
    },
    {
      id: 4,
      imgUrl: user4,
      name: "Edna",
      lastName: "Jasse",
      age: 23,
      city: "Maputo Cidade",
      country: "MOZ",
    },
    {
      id: 5,
      imgUrl: user5,
      name: "Ralina",
      lastName: "Muchisse",
      age: 22,
      city: "Maputo Cidade",
      country: "MOZ",
    },
    {
      id: 6,
      imgUrl: user6,
      name: "Olivia",
      lastName: "Miller",
      age: 27,
      city: "Berlin",
      country: "Germany",
    },
    {
      id: 7,
      imgUrl: user7,
      name: "Nady",
      lastName: "Wilson",
      age: 31,
      city: "Toronto",
      country: "Canada",
    },
    {
      id: 8,
      imgUrl: user8,
      name: "Sophia",
      lastName: "Moore",
      age: 29,
      city: "Tokyo",
      country: "Japan",
    },
    {
      id: 9,
      imgUrl: user9,
      name: "Diana",
      lastName: "Taylor",
      age: 32,
      city: "Mumbai",
      country: "India",
    },
    {
      id: 10,
      imgUrl: user4,
      name: "Yula",
      lastName: "Emanuel",
      age: 30,
      city: "Maputo cidade",
      country: "MOZ",
    },
  ];
  
  export const profileData = [
    {
      name: "Jacob Jones",
      age: 30,
      imgUrl: profile,
      hobbies: ["Caminhadas", "fotografias", "culinaria"],
      bio: "Sou uma pessoa aventureira que adora explorar novos lugares, experimentar diferentes cozinhas, captar momentos através da fotografia e passar tempo na natureza. Gosto de fazer caminhadas nos finais de semana e experimentar novas receitas na cozinha. Viajar e conhecer culturas diferentes são algumas das minhas maiores paixões e estou sempre em busca da minha próxima aventura.",
    },
  ];